#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

git diff --exit-code --stat -- . ':!node_modules' \
    || (echo "##[error] found changed files after build. please 'yarn build && npm run format'" \
             "and check in all changes" \
        && exit 1)
