on:
  workflow_dispatch:
    inputs:
      token:
        description: 'The Github token.'
        required: false
      owner:
        description: "The account owner of the repository."
        required: false
        type: string
      repo:
        description: "The name of the repository."
        required: false
        type: string
      tag_name:
        description: "The name of the tag."
        required: false
        type: string
      target_commitish:
        description: "Specifies the commitish value"
        required: false
        type: string
      name:
        description: "The name of the release."
        required: false
        type: string
      body:
        description: "Text describing the contents of the tag."
        required: false
        type: string
      draft:
        description: "true to create a draft (unpublished) release"
        required: false
        default: "false"
        type: boolean
      prerelease:
        description: "true to identify the release as a prerelease."
        required: false
        default: "false"
        type: boolean
      discussion_category_name:
        description: "If specified, a discussion of the specified category is created and linked to the release."
        required: false
        type: string
      generate_release_notes:
        description: "Whether to automatically generate the name and body for this release."
        required: false
        type: boolean
jobs:

  create_release_job:
    runs-on: ubuntu-latest
    name: A job to create a release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create A Release
        uses: ./ # Uses an action in the root directory
        with:
          token: ${{ inputs.token }}
          owner: ${{ inputs.owner }}
          repo: ${{ inputs.repo }}
          tag_name: ${{ inputs.tag_name }}
          target_commitish: ${{ inputs.target_commitish }}
          name: ${{ inputs.name }}
          body: ${{ inputs.body }}
          draft: ${{ inputs.draft }}
          prerelease: ${{ inputs.prerelease }}
          discussion_category_name: ${{ inputs.discussion_category_name }}
          generate_release_notes: ${{ inputs.generate_release_notes }}